### PR TITLE
Little proposal: warnings, check nans, stats

### PR DESCRIPTION
**Pull request by CKPEIIKA**
Introduce warnings, checking function, stat button. Probably we do not need a button for this purpose. Also a small workaround for "russian excel csv" but it seems a bit dangerous for now.

### CODE REVIEW

**Review by quantum-entangled — COMMENTED** [review]
I checked it, everything seems great. But there is a question with warnings. Should we allow users to proceed next with missing values, etc.? Because it will eventually raise an error in the following sections (e.g. training)

**Comment by quantum-entangled** [comment]
> I think non numeric values can definitely break something but user should be allowed at least to take a look on a datagrid. Missing values can be automatically filled by zeros, though I can't imagine from where such data can come from.

Ok, I guess we can leave it as it is, and later change some things by the users' requests. Do you plan to add anything else here or I could close PR and Issues?

**Comment by CKPEIIKA** [comment]
I think it can be closed. Probably when there will be the tests there would be need to change something.

**Comment by quantum-entangled** [comment]
All right. You can reopen Issues later if needed.

**Pull request merged**
